linters:
  enable:
    - gofmt
    - goimports
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/scagogogo/cwe

run:
  timeout: 5m
  tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck 